ALTER TABLE ORM.OPT_PARAMETROS ADD (valorbkp VARCHAR2(1000 BYTE));

UPDATE ORM.OPT_PARAMETROS SET valorbkp = valor;

UPDATE ORM.OPT_PARAMETROS SET valor = NULL;     

ALTER TABLE ORM.OPT_PARAMETROS MODIFY valor LONG;   
ALTER TABLE ORM.OPT_PARAMETROS MODIFY valor CLOB;

UPDATE ORM.OPT_PARAMETROS SET valor = valorbkp;

ALTER TABLE ORM.OPT_PARAMETROS DROP COLUMN valorbkp;

ALTER INDEX ORM.OPT_PARAMETROS_PK REBUILD;